Добавление функциональности «Поиск»
uncle-sly/java-filmorate pull request #11
Opened 2024-11-10 19:46 UTC by haribo0372

2024-11-11 14:07 UTC, undefbear commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                    "Неверное значение параметра 'by'. Доступные варианты: director,title, director, title");
director,title, director, title
будто бы не очень понятно написано
может другой разделитель сделать: Доступные варианты: director,title; director; title.

2024-11-11 14:07 UTC, undefbear commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new ValidationException(
все проверки на валидацию в этом проекте реализованы в слое сервиса, может тоже унести это в сервис?

2024-11-11 14:07 UTC, undefbear commented on src/main/java/ru/yandex/practicum/filmorate/validation/SearchParamBy.java
> +    }
кажется тут можно воспользоваться аннотацией @RequiredArgsConstructor для генерации конструктора с final полями

2024-11-12 08:46 UTC, haribo0372 commented on src/main/java/ru/yandex/practicum/filmorate/validation/SearchParamBy.java
> +    }
можно, но это дело вкуса

2024-11-12 12:26 UTC, uncle-sly requested changes

2024-11-12 12:26 UTC, uncle-sly commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +
лишние пробелы стоит убрать

2024-11-12 12:26 UTC, uncle-sly commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
Этот класс разве относится к разработке этой фичи?

2024-11-12 12:26 UTC, uncle-sly commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceImpl.java
> +            throw new jakarta.validation.ValidationException(
почему бы не использовать уже имеющееся в проекте ValidationException?

2024-11-12 12:26 UTC, uncle-sly commented on src/main/java/ru/yandex/practicum/filmorate/validation/SearchParamBy.java
> +
Если придет DIRECTOR, direCTOr, TITLE, tiTLe ?

2024-11-12 12:26 UTC, uncle-sly commented on src/main/java/ru/yandex/practicum/filmorate/repository/inDatabase/JdbcFilmRepository.java
>          fillGenres(films);
метод хорошо бы назвать единообразно с методом fillUpDirectors, т.е. fillUpGenres.
привести метод единообразно с fillUpDirectors, в частности запрос оставить в исходном методе. 
при таком варианте у нас получается часть методов реализована с одной логикой, часть с другой, что ухудшает чтение и понимание кода. и в целом  может вызвать доп вопросы на ревью, чем если бы это было одинаково.

2024-11-12 12:26 UTC, uncle-sly commented on src/main/java/ru/yandex/practicum/filmorate/repository/inDatabase/JdbcFilmRepository.java
> +        foundByTitle.forEach(film -> {
стоит рассмотреть возможность использовать приватный метод для жанров

2024-11-12 12:26 UTC, uncle-sly commented on src/main/java/ru/yandex/practicum/filmorate/repository/inDatabase/JdbcFilmRepository.java
> +        if (by.contains("director")) {
у тебя вроде бы есть enum , может быть стоит рассмотреть его использование?

2024-11-12 12:26 UTC, uncle-sly commented on src/main/java/ru/yandex/practicum/filmorate/repository/inDatabase/JdbcFilmRepository.java
> +    public Collection<Film> search(String query, String by) {
метод лучше назвать исходя из того что он делает или должен сделать, так легче читается.
p.s. метод сложно читать, если останется время, было бы неплохо оптимизировать его в этом плане, если возможно.

2024-11-12 12:49 UTC, semigris approved these changes, later dismissed

2024-11-12 18:44 UTC, haribo0372 commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
какой класс ?

2024-11-12 18:51 UTC, haribo0372 commented on src/main/java/ru/yandex/practicum/filmorate/repository/inDatabase/JdbcFilmRepository.java
> +        if (by.contains("director")) {
не, не хочу

2024-11-12 18:52 UTC, haribo0372 commented on src/main/java/ru/yandex/practicum/filmorate/repository/inDatabase/JdbcFilmRepository.java
> +    public Collection<Film> search(String query, String by) {
метод называется search, сам метод ищет фильмы, в чем вопрос ?

2024-11-12 19:14 UTC, semigris approved these changes

2024-11-12 21:16 UTC, uncle-sly commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
этот, Review.java

2024-11-12 21:17 UTC, uncle-sly approved these changes

2024-11-13 02:37 UTC, merged